"""add field confirmed

Revision ID: 070bdf0011d0
Revises: bfbbffcde108
Create Date: 2023-04-23 18:43:38.461493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070bdf0011d0'
down_revision = 'bfbbffcde108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
